
import React, { useEffect, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import supabase from '../lib/supabaseClient';
import './AdminAuthModal.css';

const AdminAuthModal = ({ isOpen, onClose }) => {
  const navigate = useNavigate();
  const [step, setStep] = useState(1); // 1: login, 2: otp, 3: privacy warning
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [email, setEmail] = useState('');
  const [otp, setOtp] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);
  const [adminData, setAdminData] = useState(null);
  const [generatedOtp, setGeneratedOtp] = useState('');
  const [isVerifying, setIsVerifying] = useState(false);

  useEffect(() => {
    if (!isOpen) {
      // reset state when modal closes
      setStep(1);
      setUsername('');
      setPassword('');
      setEmail('');
      setOtp('');
      setShowPassword(false);
      setError('');
      setLoading(false);
      setAdminData(null);
      setGeneratedOtp('');
    }
  }, [isOpen]);

   
  useEffect(() => {
    const onKey = (e) => {
      if (!isOpen) return;
      if (e.key === 'Escape') onClose();
      // Allow Enter to submit based on current step
      if (e.key === 'Enter' && !loading) {
        if (step === 1) handleLoginSubmit(e);
        else if (step === 2) handleOtpSubmit(e);
        else if (step === 3) handlePrivacyAccept();
      }
    };

    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [isOpen, step, username, password, email, otp, loading]);

  if (!isOpen) return null;

  const handleOverlayClick = (e) => {
    if (e.target.className === 'admin-auth-overlay') {
      onClose();
    }
  };

  // Step 1: Login validation
  const validateLogin = () => {
    setError('');
    const user = String(username || '').trim();
    const pass = String(password || '');
    if (!user) return setError('Username is required');
    if (!/^\w{3,30}$/.test(user)) return setError('Username must be 3-30 characters and contain only letters, numbers, or underscores');
    if (!pass) return setError('Password is required');
    if (pass.length < 6) return setError('Password must be at least 6 characters');
    return null;
  };

  // Step 1: Handle login submission
  const handleLoginSubmit = async (e) => {
    if (e && e.preventDefault) e.preventDefault();
    const v = validateLogin();
    if (v) return;
    setLoading(true);
    setError('');

    try {
      // Query the adminauth table for matching username and password
      const { data, error: supaError } = await supabase
        .from('adminauth')
        .select('*')
        .eq('username', username.trim())
        .eq('password', password)
        .single();

      if (supaError || !data) {
        setError('Invalid credentials');
        setLoading(false);
        return;
      }

      setAdminData(data);
      setLoading(false);
      setStep(2); // Move to OTP step
    } catch {
      setError('Network error ΓÇö please try again');
      setLoading(false);
    }
  };

  // Step 2: Generate and send OTP
  const generateOtp = () => {
    return Math.floor(100000 + Math.random() * 900000).toString(); // 6-digit OTP
  };

  const sendOtpEmail = async (email, otpCode) => {
    const isLocalDev = import.meta.env.DEV || window.location.hostname === 'localhost';

    try {
      // Use backend API for email sending (it has Nodemailer configured)
      const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5174';
      const backendResponse = await fetch(`${API_URL}/api/auth/send-otp`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          email: email
        })
      });

      const result = await backendResponse.json().catch(() => ({}));
      
      if (backendResponse.ok && result.success) {
        // Use the OTP generated by the backend
        setGeneratedOtp(result.otp);
        console.log('Γ£à OTP sent via backend email service');
        return { 
          success: true, 
          method: 'backend',
          otp: result.otp 
        };
      }

      // Backend reached but email send failed: show real error (no silent fallback in production).
      return {
        success: false,
        method: 'backend-error',
        error: result.details || result.error || `OTP request failed (${backendResponse.status})`
      };
    } catch (error) {
      console.error('Γ¥î Backend email service error:', error);

      if (!isLocalDev) {
        return {
          success: false,
          method: 'network-error',
          error: 'Unable to reach OTP service. Please try again in a few moments.'
        };
      }
      
      // Local/dev fallback only.
      console.log(`≡ƒöÉ OTP Fallback for ${email}: ${otpCode}`);
      setGeneratedOtp(otpCode);
      return { 
        success: true, 
        method: 'fallback',
        message: 'Email service temporarily unavailable. OTP shown in console for demo.',
        otp: otpCode
      };
    }
  };

  const handleSendOtp = async () => {
    if (!email || !/\S+@\S+\.\S+/.test(email)) {
      setError('Please enter a valid email address');
      return;
    }

    setLoading(true);
    setError('');

    const otpCode = generateOtp();
    const result = await sendOtpEmail(email, otpCode);

    if (result.success) {
      // Use OTP from backend response or fallback
      const actualOtp = result.otp || otpCode;
      setGeneratedOtp(actualOtp);
      setError(''); // Clear any previous errors
      
      const successMessage = result.method === 'backend' 
        ? `Γ£à OTP sent to ${email} via secure email service.\n\nCheck your email for the verification code.`
        : result.method === 'fallback'
        ? `ΓÜá∩╕Å ${result.message}\n\nYour OTP: ${actualOtp}`
        : `Γ£à OTP sent to ${email}`;
        
      alert(successMessage);
    } else {
      setError(result.error || 'Failed to send OTP');
    }

    setLoading(false);
  };

  // Step 2: Handle OTP verification
  const handleOtpSubmit = async (e) => {
    if (e && e.preventDefault) e.preventDefault();
    
    if (!otp || otp.length !== 6) {
      setError('Please enter the 6-digit OTP');
      return;
    }

    if (otp !== generatedOtp) {
      setError('Invalid OTP. Please try again.');
      return;
    }

    setError('');
    setIsVerifying(true);
    
    // Simulate verification process with loading animation
    setTimeout(() => {
      setIsVerifying(false);
      setStep(3); // Move to privacy warning
    }, 2000); // 2 second loading animation
  };

  // Step 3: Handle privacy acceptance
  const handlePrivacyAccept = () => {
    try { 
      sessionStorage.setItem('adminAuthed', 'true');
      sessionStorage.setItem('adminUser', JSON.stringify(adminData));
    } catch (err) { 
      console.warn('Session storage error:', err);
    }

    onClose();
    navigate('/admin/inventory');
  };

  return (
    <div className="admin-auth-overlay" onClick={handleOverlayClick}>
      <div className="admin-auth-modal" role="dialog" aria-modal="true" aria-label="Admin authentication">
        <button className="admin-auth-close" onClick={onClose} aria-label="Close">
          ├ù
        </button>

        <div className="admin-auth-content">
          {/* Step 1: Login */}
          {step === 1 && (
            <>
              <div className="admin-auth-icon">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                  <path fillRule="evenodd" d="M12 1.5a5.25 5.25 0 00-5.25 5.25v3a3 3 0 00-3 3v6.75a3 3 0 003 3h10.5a3 3 0 003-3v-6.75a3 3 0 00-3-3v-3c0-2.9-2.35-5.25-5.25-5.25zm3.75 8.25v-3a3.75 3.75 0 10-7.5 0v3h7.5z" clipRule="evenodd" />
                </svg>
              </div>

              <h2>Admin Access</h2>
              <p>NOTE!: Do not make uncertain decisions, You know who we are! ≡ƒÿê</p>
              

              <form className="admin-auth-form" onSubmit={handleLoginSubmit}>
                <label htmlFor="admin-username">Username</label>
                <input
                  id="admin-username"
                  name="username"
                  type="text"
                  value={username}
                  onChange={(e) => setUsername(e.target.value)}
                  autoComplete="username"
                  required
                  minLength={3}
                  maxLength={30}
                />

                <label htmlFor="admin-password">Password</label>
                <div className="admin-auth-password-wrap">
                  <input
                    id="admin-password"
                    name="password"
                    type={showPassword ? 'text' : 'password'}
                    value={password}
                    onChange={(e) => setPassword(e.target.value)}
                    autoComplete="current-password"
                    required
                    minLength={6}
                  />
                  <button
                    type="button"
                    className="admin-auth-showpass"
                    onClick={() => setShowPassword((s) => !s)}
                    aria-label={showPassword ? 'Hide password' : 'Show password'}
                  >
                    {showPassword ? 'Hide' : 'Show'}
                  </button>
                </div>

                {error && <div className="admin-auth-error" role="alert">{error}</div>}

                <div className="admin-auth-actions admin-auth-actions-form">
                  <button className="admin-auth-btn admin-auth-login" type="submit" disabled={loading}>
                    {loading ? 'VerifyingΓÇª' : 'Continue'}
                  </button>
                  <button className="admin-auth-btn admin-auth-cancel" type="button" onClick={onClose} disabled={loading}>
                    Cancel
                  </button>
                </div>
              </form>
            </>
          )}

          {/* Step 2: OTP Verification */}
          {step === 2 && (
            <>
              <div className="admin-auth-icon">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M1.5 8.67v8.58a3 3 0 003 3h15a3 3 0 003-3V8.67l-8.928 5.493a3 3 0 01-3.144 0L1.5 8.67z" />
                  <path d="M22.5 6.908V6.75a3 3 0 00-3-3h-15a3 3 0 00-3 3v.158l9.714 5.978a1.5 1.5 0 001.572 0L22.5 6.908z" />
                </svg>
              </div>

              <h2>Email Verification</h2>
              

              <form className="admin-auth-form" onSubmit={handleOtpSubmit}>
                <label htmlFor="admin-email">Email Address</label>
                <div className="admin-auth-email-group">
                  <input
                    id="admin-email"
                    name="email"
                    type="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    placeholder="Enter your email for OTP"
                    required
                  />
                  <button
                    type="button"
                    className="admin-auth-send-otp"
                    onClick={handleSendOtp}
                    disabled={loading || !email}
                  >
                    {loading ? 'Sending...' : 'Send OTP'}
                  </button>
                </div>

                {generatedOtp && (
                  <>
                    <label htmlFor="admin-otp">Enter OTP Code</label>
                    <input
                      id="admin-otp"
                      name="otp"
                      type="text"
                      value={otp}
                      onChange={(e) => setOtp(e.target.value)}
                      placeholder="6-digit code"
                      maxLength={6}
                      required
                    />
                  </>
                )}

                {error && <div className="admin-auth-error" role="alert">{error}</div>}

                <div className="admin-auth-actions admin-auth-actions-form">
                  <button 
                    className="admin-auth-btn admin-auth-login" 
                    type="submit" 
                    disabled={!generatedOtp || !otp || otp.length !== 6}
                  >
                    Verify OTP
                  </button>
                  <button 
                    className="admin-auth-btn admin-auth-cancel" 
                    type="button" 
                    onClick={() => setStep(1)}
                  >
                    Back
                  </button>
                </div>
              </form>
            </>
          )}

          {/* Loading Animation - After OTP Verification */}
          {isVerifying && (
            <>
              <div className="admin-auth-icon admin-auth-loading">
                <div className="admin-auth-spinner"></div>
              </div>

              <h2>Verifying Your Identity</h2>
              
              <div className="admin-auth-loading-content">
                <p className="admin-auth-loading-text">Authenticating admin credentials...</p>
                <div className="admin-auth-progress-bar">
                  <div className="admin-auth-progress-fill"></div>
                </div>
                <p className="admin-auth-loading-subtext">Please wait while we verify your access...</p>
              </div>
            </>
          )}

          {/* Step 3: Privacy Warning */}
          {step === 3 && !isVerifying && (
            <>
              <div className="admin-auth-icon admin-auth-warning">
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor">
                  <path fillRule="evenodd" d="M9.401 3.003c1.155-2 4.043-2 5.197 0l7.355 12.748c1.154 2-.29 4.5-2.599 4.5H4.645c-2.309 0-3.752-2.5-2.598-4.5L9.4 3.003zM12 8.25a.75.75 0 01.75.75v3.75a.75.75 0 01-1.5 0V9a.75.75 0 01.75-.75zm0 8.25a.75.75 0 100-1.5.75.75 0 000 1.5z" clipRule="evenodd" />
                </svg>
              </div>

              <div className="admin-auth-intro-text">
                <p>
                  You probably know what 
                  <a href="https://privacy.gov.ph/data-privacy-act/" target="_blank" rel="noopener noreferrer"> RA 10173 </a>
                  is, right?
                </p>
                <p>You know sometimes it's okay to be ALONE :)</p>
              </div>
              

              <div className="admin-auth-privacy-content">
                <div className="admin-auth-warning-box">
                  <h3>ΓÜá∩╕Å Confidential System Access</h3>
                  <p>You are about to access the <strong>Administrative Inventory Management System</strong>. This system contains sensitive business data including:</p>
                  
                  <ul>
                    <li>≡ƒöÉ Product inventory and pricing information</li>
                    <li>≡ƒôè Sales data and business analytics</li>
                    <li>≡ƒÆ░ Financial records and transactions</li>
                    <li>≡ƒæÑ Customer information and order history</li>
                  </ul>
                  
                  <div className="admin-auth-terms">
                    <h4>Terms of Access:</h4>
                    <p>ΓÇó All activities are logged and monitored</p>
                    <p>ΓÇó Unauthorized access or misuse is strictly prohibited</p>
                    <p>ΓÇó Data must be handled in accordance with privacy laws</p>
                    <p>ΓÇó You are responsible for maintaining data confidentiality</p>
                  </div>
                </div>
              </div>

              <div className="admin-auth-actions">
                <button 
                  className="admin-auth-btn admin-auth-login" 
                  onClick={handlePrivacyAccept}
                >
                  I Understand & Accept
                </button>
                <button 
                  className="admin-auth-btn admin-auth-cancel" 
                  onClick={onClose}
                >
                  Decline
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default AdminAuthModal;
